Limarenko aa
AlexeySachkov/is-labs pull request #10
Opened 2020-11-02 17:59 UTC by dreary-merlin

М20-ИСТ-1

2020-11-04 18:32 UTC, AlexeySachkov requested changes

2020-11-04 18:32 UTC, AlexeySachkov commented on limarenko/lab1/lab1.pro
> +решение(y,1,0,0,0) :- выход(y), вход(x1,0), вход(x2,0), вход(x3,0). %правило1
Какую роль в этом правиле играет параметр `y`?

Можно ли как-то переписать это правило, чтобы автоматически вычислять результат не описывая целиком таблицу истинности?

2020-11-04 18:32 UTC, AlexeySachkov commented on limarenko/lab1/lab1.pro
> +результат(K,Y,X1,X2,X3) :- выход(K), вход(x1,X1), X1=0, вход(x2,X2), X2=0, вход(x3,X3), X3=0, Y=1; %правило9
Почему правило `решение` не используется никаким образом?

Какое назначение у правила `результат`?

2020-11-04 19:02 UTC, dreary-merlin commented on limarenko/lab1/lab1.pro
> +решение(y,1,0,0,0) :- выход(y), вход(x1,0), вход(x2,0), вход(x3,0). %правило1
y - код выходного сигнала, нужен, чтобы показать, что вычисляется y, а не x.
да, правило 9 - универсальное правило и решение задачи.

2020-11-04 19:07 UTC, dreary-merlin commented on limarenko/lab1/lab1.pro
> +результат(K,Y,X1,X2,X3) :- выход(K), вход(x1,X1), X1=0, вход(x2,X2), X2=0, вход(x3,X3), X3=0, Y=1; %правило9
на основе частных правил создается универсальное правило.
правило 9 - решение задачи.

2020-11-24 18:48 UTC, AlexeySachkov requested changes

2020-11-24 18:48 UTC, AlexeySachkov commented on limarenko/lab1/lab1.pro
> +выход(K), вход(x1,X1), not(X1=0), вход(x2,X2), вход(x3,X3), Y=0.
Есть какая-либо возможность сократить этот кусок кода?

2020-11-25 11:31 UTC, dreary-merlin commented on limarenko/lab1/lab1.pro
> +выход(K), вход(x1,X1), not(X1=0), вход(x2,X2), вход(x3,X3), Y=0.
да
выход(K), вход(x1,X1), вход(x2,X2), вход(x3,X3), (X1+X2+X3)>0, Y=0.

2020-11-26 12:57 UTC, dreary-merlin commented on limarenko/lab1/lab1.pro
> +выход(K), вход(x1,X1), not(X1=0), вход(x2,X2), вход(x3,X3), Y=0.
с рекурсией:
Дан список. Убедиться, что все элементы, стоящие на четных местах, расположены в порядке возрастания, а на нечетных – в порядке убывания. Первые 7 элементов списка этому требованию могут не удовлетворять.
DOMAINS
список=integer*

PREDICATES
nondeterm отбросить(список,список)
nondeterm сортировка(string,список,string)

CLAUSES
отбросить([_,_,_,_,_,_,_|Tail],Tail). %ф1
сортировка(A,[B,G,C,H|D],E):- B<C, G>H, !, A<>"notsorted", сортировка("sorted",[C,H|D],E). %пр1
сортировка(A,[B,G,C,H|D],E):- !, B>C, G<H, A<>"sorted", сортировка("notsorted",[C,H|D],E). %пр2
сортировка(A,_,A). %ф2

GOAL
отбросить([1,2,6,3,5,1,4,2,9,7,1,8],Gtail), сортировка("no",Gtail,Sort).
/*
1. Цель отбросить([1,2,6,3,5,1,4,2,9,7,1,8],Gtail), сортировка("no",Gtail,Sort).
   Решение Gtail=[2,9,7,1,8], Sort=sorted
   1 Solution
*/

2020-11-29 11:55 UTC, AlexeySachkov approved these changes

2022-09-30 09:09 UTC, closed without merging