First commit
AlexeySachkov/is-labs pull request #20
Opened 2020-11-12 11:56 UTC by AndreyKomanetsky

2020-11-21 11:15 UTC, AlexeySachkov requested changes

2020-11-21 11:15 UTC, AlexeySachkov commented on M20-IST-3_KOMANETSKY_LAB1.PRO
> +  нравится(билл,Предпочтение):-	нравится(клара, Предпочтение).%п. 1
Просьба добавить комментарий к этому предикату

2020-11-21 11:15 UTC, AlexeySachkov commented on M20-IST-3_KOMANETSKY_LAB1.PRO
> +  %нравится(мэрри, детектив):- нравится(алекс, детектив). %п. 3б
Почему эти правила закомментированы?

2020-11-21 11:15 UTC, AlexeySachkov commented on M20-IST-3_KOMANETSKY_LAB1.PRO
> +  %мэрри нравится детектив если алекс любит детектив.
Этот комментарий не соответствует предикату выше

2020-11-22 12:55 UTC, AndreyKomanetsky commented on M20-IST-3_KOMANETSKY_LAB1.PRO
> +  %нравится(мэрри, детектив):- нравится(алекс, детектив). %п. 3б
Это были не закоментированные правила, а то, как бы выглядело предыдущее правило с конструкцией ИЛИ, если бы его разбили на два самостоятельных правила. Я исправил эти коментарии на более удобоваримые

2020-11-24 19:17 UTC, AlexeySachkov approved these changes

2024-02-14 16:59 UTC, closed without merging