Komanetsky lab2
AlexeySachkov/is-labs pull request #30
Opened 2020-11-22 13:25 UTC by AndreyKomanetsky

2020-11-29 13:23 UTC, AlexeySachkov requested changes

2020-11-29 13:23 UTC, AlexeySachkov commented on M20-IST-3_KOMANETSKY_LAB1.PRO
> +PREDICATES
Если это pull request для второй лабораторки, просьба убрать из него файлы к первой лабораторной

2020-11-29 13:23 UTC, AlexeySachkov commented on lab2.py
> +    start_loop(agents)
Выглядит интересно, но сходу немного сложно проследить за всей цепочкой общения клиентов. Просьба добавить в комментариях пример вывода программы, как это сделано в #38

2020-11-30 07:09 UTC, AndreyKomanetsky commented on lab2.py
> +    start_loop(agents)
Я удалил все ненужные файлы и добавил примеры выводов программы на экран в файл README_lab2

2020-12-01 21:38 UTC, AlexeySachkov approved these changes

2024-02-14 16:59 UTC, closed without merging