Limarenko lab2
AlexeySachkov/is-labs pull request #51
Opened 2020-11-30 19:39 UTC by dreary-merlin

2020-12-17 14:01 UTC, AlexeySachkov requested changes

2020-12-17 14:01 UTC, AlexeySachkov commented on lab2/Client.py
> +        call_later(10.0, self.buy_the_ticket)
Почему это действие происходит по timeout-у, а не как ответ на сообщение о цене билета? Аналогичный вопрос про покупку еды

2020-12-18 11:56 UTC, dreary-merlin commented on lab2/Client.py
> +        call_later(10.0, self.buy_the_ticket)
чтобы регулировать очередность обращения к продавцам

2020-12-21 16:13 UTC, AlexeySachkov commented on lab2/Client.py
> +        call_later(10.0, self.buy_the_ticket)
> чтобы регулировать очередность обращения к продавцам

Просьба немного переписать код, чтобы запрос покупки билета осуществлялся как ответ на его стоимость, т.е. вызов `buy_the_ticket` должен быть где-то внутри метода `react`

2020-12-21 18:59 UTC, dreary-merlin commented on lab2/Client.py
> +        call_later(10.0, self.buy_the_ticket)
исправлено

2020-12-27 12:38 UTC, AlexeySachkov approved these changes

2022-09-30 09:09 UTC, closed without merging