Лабораторная работа 2
AlexeySachkov/is-labs pull request #61
Opened 2020-12-02 05:55 UTC by KristinaStaroverova

М20-ИСТ-2 Староверова Кристина

2020-12-11 09:56 UTC, closed without merging

2020-12-17 17:53 UTC, AlexeySachkov requested changes

2020-12-17 17:53 UTC, AlexeySachkov commented on Староверова/2/lab2.py
> +#Имеются весы с чашами, которые необходимо уравнять.
Просьба добавить пример работы программы в код в виде комментариев

2020-12-18 16:51 UTC, KristinaStaroverova commented on Староверова/2/lab2.py
> +#Имеются весы с чашами, которые необходимо уравнять.
Обновила файл.

2020-12-21 14:18 UTC, AlexeySachkov approved these changes