Dubrovin M20-IST-5
AlexeySachkov/is-labs pull request #7
Opened 2020-11-01 20:36 UTC by alex327512

2020-11-01 20:36 UTC, alex327512 commented
Lab #1

2020-11-02 17:01 UTC, AlexeySachkov requested changes

2020-11-02 17:01 UTC, AlexeySachkov commented on lab1.pl
> +married(roy,sarah).
Этот предикат нигде не используется, может он не нужен тогда? Или наоборот его тоже можно вывести из имеющихся данных (считая, что у нас нет внебрачных детей)

2020-12-01 19:20 UTC, alex327512 commented
![family-tree](https://user-images.githubusercontent.com/48681897/100786549-5fc24900-3423-11eb-98aa-b8ed486012c2.jpg)

2020-12-01 21:20 UTC, AlexeySachkov approved these changes

2023-10-14 22:12 UTC, closed without merging