Орлов Денис м20-ист3
AlexeySachkov/is-labs pull request #75
Opened 2020-12-10 16:28 UTC by ORLVNIMUSIC

Выбор старосты в группе
Агент Chooser - человек, который выдвигает кандидатуру на пост старосты в группе (случайным образом).
Агент Solver - человек, принимающий решение, основываясь на успеваемости студента.
Chooser предлагает сделать одного студента старостой -> Solver смотрит на его оценки, и если успеваемость студента не удовлетворяет условиям, то Chooser выбирает заново.

2020-12-22 19:36 UTC, AlexeySachkov requested changes

2020-12-22 19:36 UTC, AlexeySachkov commented on Орлов Денис М20-ИСТ3/2/program.py
> +#Выбор старосты в группе
В чем основные отличия от #74?

2020-12-22 19:36 UTC, AlexeySachkov commented on Орлов Денис М20-ИСТ3/2/program.py
> +        if (message.performative == ACLMessage.PROPOSE and answerSTR == "Good"):
Зачем проверять `performative` в ветке `else` ещё раз?

2020-12-23 12:34 UTC, ORLVNIMUSIC commented on Орлов Денис М20-ИСТ3/2/program.py
> +#Выбор старосты в группе
Мы с Романовым находились на связи во время написания программ из-за проблем с pade
Пока общались, делились мнениями по поводу тем для агентов, и поэтому варианты реализации могли совпасть (случайно)
Каждый писал свою программу сам, но мы помогали друг другу в тупиках

2020-12-23 12:35 UTC, ORLVNIMUSIC commented on Орлов Денис М20-ИСТ3/2/program.py
> +        if (message.performative == ACLMessage.PROPOSE and answerSTR == "Good"):
Я еще не знал, будет ли у меня еще один тип сообщения отсылаться от другого агента, когда я писал этот блок
Я просто не убрал проверку, так как забыл, что других типов сообщений так и не реализовал

2020-12-30 18:15 UTC, AlexeySachkov approved these changes

2022-10-27 22:11 UTC, closed without merging